.include <bsd.own.mk>

PROG=		xvmware
SRCS=		xvmware.c \
		xlanginfo.c \
		vmbackdoor_wrapper.c \
		vmmouse_proto.c \
		iconv_wrapper.c

APPDEFS=	Xvmware.ad
MKMAN=		no

CFLAGS+=	-g
LDADD+=		-lXmu -lXt
DPADD+=		${LIBXMU} ${LIBXT}

.include <bsd.x11.mk>
.include <bsd.prog.mk>
